### ISSUE TITLE
CRITICAL: Can load more than maximum capacity of cars

### ISSUE THREAD

**Issue by I-Hansson** [Martin-L-Git/Lab-1#11]
At the moment we can load infinitely many cars with the help of getLoadedCars() method. 

https://github.com/Martin-L-Git/Lab-1/blob/fef146b3bb46bc8924579add684b36b4c11a6ac4/src/CarStorage.java#L38-L40

**Comment by gababool** [comment]
How? We cannot solve this in time, so please give us a hint :)

**Comment by I-Hansson** [comment]
https://github.com/Martin-L-Git/Lab-1/blob/fef146b3bb46bc8924579add684b36b4c11a6ac4/src/CarRepairShop.java#L23-L25

Eftersom metoden är public kan vi hämta(get) referensen till hela listan med bilar. Vi kan enkelt lägga till bilar då: som exempel:

getLoadedCars().add(car);
Då går vi förbi load metoden och kan lägga till bilar utan att behöver bry oss om en bil är i rörelse, är nära eller det är fullt i "garaget".

**Comment by gababool** [comment]
Men add() kommer vi ju aldrig kalla på, eftersom de fordonen som har ett carStorage har sina egna metoder load och unload som man använder.

**Comment by I-Hansson** [comment]
Load/unload borde enbart vara de metoder som kan användas för att ladda/tabort bilar. Vi vill göra vår kod så säker som möjligt genom att man enbart kan använda dem metoderna.
Ett sätt man kan lösa det på är att ta bort gettern och ett annat är att använda sig av defensive copying.

**Comment by gababool** [comment]
Fixar det imorgon på exercise

**Comment by gababool** [comment]
@I-Hansson 

Förresten, kan man inte lösa det genom att bara köra en vanlig Array med bestämd storlek, och i loadCar metoden så kan man bara lägga till en for-loop som lägger bilen man skickar med på en bestämd plats, om det finns en.

På så sätt kan man inte använda add()-metoden och lägga till en bil om arrayn är full, eller hur?

**Comment by gababool** [comment]
Kolla på CarStorage i den senaste versionen av koden. Skulle det som för tillfället är bortkommenterat fungera?

**Comment by gababool** [comment]
Nevermind! Tog bara bort getLoadedCars helt och hållet och lade till en metod som returnerar storleken på listan istället.

Ingenstans i koden användes getLoadedCars förutom när vi ville veta storleken, så allt fungerar som det borde nu.

Har fortfarande kvar den andra lösningen i CarStorage om du vill kolla på den :)

**Comment by I-Hansson** [comment]
Bra jobbat! Om ni skulle ha använt en fixed-size array så skulle ni få ett **ArrayIndexOutOfBoundsException** när ni la till en bil när listan vart full.
